### ISSUE TITLE
redis设置了端口号位6679后,运行项目报错,提示连接失败.仍然按照默认6379进行连接.看来是配置没有读取到.

### ISSUE THREAD

**Issue by fromciom** [binarywang/wx-java-mp-demo#2]

**Comment by fromciom** [comment]
redis设置了端口号位6679后,运行项目报错,提示连接失败.仍然按照默认6379进行连接.看了是配置没有读取到.

**Comment by binarywang** [comment]
你是使用的redistemplate吧？那个端口和ip的配置确实无法生效，因为使用的是你自己系统已经定义的redistemplate，无需从新配置
